version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: security_db
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - security_db_data:/var/lib/postgresql/data

volumes:
  security_db_data:

